default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        args: [--config-file=pyproject.toml]
        require_serial: true
        language: system
        types: [python]
        exclude: "tests"
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: debug-statements
