version: "3.9"

services:

  zookeeper:
      image: bitnami/zookeeper:latest
      ports:
          - 2181:2181
      environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
      networks:
        - kafka
        - grafana_example_default

  kafka:
      image: bitnami/kafka:latest
      ports:
          - 9092:9092
          - 9093:9093
          - 29092:29092
          - 7071:7071
      environment:
          - KAFKA_BROKER_ID=1
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
          - KAFKA_OPTS=-javaagent:/opt/jmx_prometheus_javaagent-1.0.1.jar=7071:/opt/kafka-jmx-config.yml
      volumes:
        - ./kafka-jmx-config.yml:/opt/kafka-jmx-config.yml # конфиг JMX Exporter
        - ./jmx_prometheus_javaagent-1.0.1.jar:/opt/jmx_prometheus_javaagent-1.0.1.jar # JMX Exporter jar
      depends_on:
          - zookeeper
      networks:
        - kafka
        - grafana_example_default


networks:
  kafka:
    driver: bridge
  grafana_example_default:
    external: true